# Generated by Django 2.1.4 on 2018-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='question',
            name='type_field',
            field=models.PositiveSmallIntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'radio'), (3, 'select'), (4, 'multi select'), (5, 'text area')]),
        ),
    ]
