# Generated by Django 5.2.3 on 2025-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0017_alter_survey_success_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="cycle_survey",
            field=models.BooleanField(
                default=False,
                help_text="If True, success page returns to survey",
                verbose_name="Cycle the survey",
            ),
        ),
    ]
